// Auto-generated by stx — do not edit
// Source: resources/views/

export const routes = [
  { pattern: '/checkout/contact', filePath: 'storage/framework/defaults/resources/views/checkout/contact.stx', isDynamic: false, params: [] },
  { pattern: '/checkout/payment', filePath: 'storage/framework/defaults/resources/views/checkout/payment.stx', isDynamic: false, params: [] },
  { pattern: '/checkout/shipping', filePath: 'storage/framework/defaults/resources/views/checkout/shipping.stx', isDynamic: false, params: [] },
  { pattern: '/emails/welcome', filePath: 'storage/framework/defaults/resources/views/emails/welcome.stx', isDynamic: false, params: [] },
  { pattern: '/errors/tester', filePath: 'storage/framework/defaults/resources/views/errors/tester.stx', isDynamic: false, params: [] },
  { pattern: '/', filePath: 'resources/views/index.stx', isDynamic: false, params: [] },
  { pattern: '/cart', filePath: 'storage/framework/defaults/resources/views/cart.stx', isDynamic: false, params: [] },
  { pattern: '/coming-soon', filePath: 'storage/framework/defaults/resources/views/coming-soon.stx', isDynamic: false, params: [] },
  { pattern: '/dashboard', filePath: 'storage/framework/defaults/resources/views/dashboard/index.stx', isDynamic: false, params: [] },
  { pattern: '/live', filePath: 'resources/views/live.stx', isDynamic: false, params: [] },
  { pattern: '/markets', filePath: 'resources/views/markets.stx', isDynamic: false, params: [] },
  { pattern: '/pricing', filePath: 'resources/views/pricing.stx', isDynamic: false, params: [] },
  { pattern: '/orders/:id', filePath: 'storage/framework/defaults/resources/views/orders/[id].stx', isDynamic: true, params: ["id"] },
] as const

export type RouteName = typeof routes[number]['pattern']
