// Auto-generated by STX - do not edit
declare module "stx/routes" {
  interface RouteMap {
    '/checkout/contact': {  }
    '/checkout/payment': {  }
    '/checkout/shipping': {  }
    '/components/FeatureCard': {  }
    '/emails/welcome': {  }
    '/errors/tester': {  }
    '/features/api': {  }
    '/features/automation': {  }
    '/features/evidence': {  }
    '/features/live': {  }
    '/features/odds': {  }
    '/features/risk': {  }
    '/features/sheets': {  }
    '/features/smart-money': {  }
    '/layouts/default': {  }
    '/layouts/marketing': {  }
    '/partials/theme': {  }
    '/': {  }
    '/cart': {  }
    '/coming-soon': {  }
    '/community': {  }
    '/dashboard': {  }
    '/features': {  }
    '/live': {  }
    '/markets': {  }
    '/pricing': {  }
    '/orders/:id': { id: string }
  }
}
