// Auto-generated by STX - do not edit
declare module "stx/routes" {
  interface RouteMap {
    '/checkout/contact': {  }
    '/checkout/payment': {  }
    '/checkout/shipping': {  }
    '/components/FeatureCard': {  }
    '/emails/welcome': {  }
    '/errors/tester': {  }
    '/layouts/default': {  }
    '/layouts/marketing': {  }
    '/partials/theme': {  }
    '/': {  }
    '/cart': {  }
    '/coming-soon': {  }
    '/dashboard': {  }
    '/live': {  }
    '/markets': {  }
    '/pricing': {  }
    '/orders/:id': { id: string }
  }
}
