CREATE TABLE IF NOT EXISTS `campaigns` (
  `id` bigint PRIMARY KEY auto_increment,
  `name` varchar(255) not null,
  `description` text,
  `type` ENUM('email', 'sms', 'push', 'social', 'multi-channel') not null,
  `status` ENUM('draft', 'scheduled', 'sending', 'sent', 'paused', 'cancelled', 'failed', 'active', 'completed', 'archived') not null default 'draft',
  `subject` varchar(255),
  `template` varchar(255),
  `text` varchar(255),
  `from_name` varchar(100),
  `from_address` varchar(255),
  `email_list_id` integer REFERENCES `email_lists`(`id`),
  `scheduled_at` datetime,
  `sent_at` datetime,
  `audience_size` integer default 0,
  `sent_count` integer default 0,
  `open_rate` integer,
  `click_rate` integer,
  `conversion_rate` integer,
  `budget` integer,
  `spent` integer default 0,
  `currency` varchar(3) not null default 'USD',
  `start_date` datetime,
  `end_date` datetime,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime,
  `uuid` varchar(255)
);
CREATE UNIQUE INDEX `campaigns_uuid_unique` ON `campaigns` (`uuid`);
