ALTER TABLE `ai_insights` MODIFY COLUMN `selection_id` bigint;
ALTER TABLE `ai_insights` MODIFY COLUMN `market_event_id` bigint;
ALTER TABLE `ai_insights` MODIFY COLUMN `caveats` text default ('');
ALTER TABLE `athletes` MODIFY COLUMN `secondary_positions` text default ('[]');
ALTER TABLE `athlete_career_records` MODIFY COLUMN `details` text default ('{}');
ALTER TABLE `athlete_identities` MODIFY COLUMN `aliases` text default ('[]');
ALTER TABLE `athlete_identities` MODIFY COLUMN `profile_facts` text default ('{}');
ALTER TABLE `athlete_season_stats` MODIFY COLUMN `metrics` text default ('{}');
ALTER TABLE `backfill_tasks` MODIFY COLUMN `last_error` text default ('');
ALTER TABLE `backfill_tasks` MODIFY COLUMN `payload` text default ('{}');
ALTER TABLE `board_columns` MODIFY COLUMN `board_id` bigint not null;
ALTER TABLE `bookmakers` MODIFY COLUMN `slug` varchar(100) not null;
ALTER TABLE `campaigns` MODIFY COLUMN `email_list_id` bigint;
ALTER TABLE `campaign_sends` MODIFY COLUMN `campaign_id` bigint not null;
ALTER TABLE `campaign_sends` MODIFY COLUMN `subscriber_id` bigint not null;
ALTER TABLE `campaign_sends` MODIFY COLUMN `email_list_id` bigint not null;
ALTER TABLE `cards` MODIFY COLUMN `board_id` bigint not null;
ALTER TABLE `card_comments` MODIFY COLUMN `card_id` bigint not null;
ALTER TABLE `card_comments` MODIFY COLUMN `user_id` bigint;
ALTER TABLE `decision_evidence` MODIFY COLUMN `trade_decision_id` bigint;
ALTER TABLE `email_list_subscribers` MODIFY COLUMN `email_list_id` bigint not null;
ALTER TABLE `email_list_subscribers` MODIFY COLUMN `subscriber_id` bigint not null;
ALTER TABLE `event_results` MODIFY COLUMN `market_event_id` bigint;
ALTER TABLE `exchange_accounts` MODIFY COLUMN `user_id` bigint;
ALTER TABLE `exchange_orders` MODIFY COLUMN `trade_decision_id` bigint;
ALTER TABLE `exchange_orders` MODIFY COLUMN `exchange_account_id` bigint;
ALTER TABLE `exchange_orders` MODIFY COLUMN `client_order_id` varchar(80);
ALTER TABLE `fair_prices` MODIFY COLUMN `best_bookmaker_id` bigint;
ALTER TABLE `fair_prices` MODIFY COLUMN `selection_id` bigint;
ALTER TABLE `ingest_runs` MODIFY COLUMN `error` text default ('');
ALTER TABLE `labels` MODIFY COLUMN `board_id` bigint not null;
ALTER TABLE `market_events` MODIFY COLUMN `home_sports_team_id` bigint;
ALTER TABLE `market_events` MODIFY COLUMN `away_sports_team_id` bigint;
ALTER TABLE `market_notes` MODIFY COLUMN `prediction_market_id` bigint;
ALTER TABLE `market_notes` MODIFY COLUMN `user_id` bigint;
ALTER TABLE `market_trades` MODIFY COLUMN `prediction_market_id` bigint;
ALTER TABLE `market_trades` MODIFY COLUMN `market_trader_id` bigint;
ALTER TABLE `notifications` MODIFY COLUMN `id` bigint;
ALTER TABLE `notifications` MODIFY COLUMN `user_id` bigint;
ALTER TABLE `notifications` MODIFY COLUMN `created_at` datetime not null default CURRENT_TIMESTAMP;
ALTER TABLE `notifications` MODIFY COLUMN `uuid` varchar(255);
ALTER TABLE `notification_deliveries` MODIFY COLUMN `user_id` bigint;
ALTER TABLE `notification_deliveries` MODIFY COLUMN `channel` varchar(255) not null;
ALTER TABLE `notification_deliveries` MODIFY COLUMN `status` varchar(255) not null default 'pending';
ALTER TABLE `notification_deliveries` MODIFY COLUMN `created_at` datetime not null default CURRENT_TIMESTAMP;
ALTER TABLE `order_idempotency` MODIFY COLUMN `order_id` bigint not null;
ALTER TABLE `selections` MODIFY COLUMN `sports_team_id` bigint;
ALTER TABLE `shipping_rates` MODIFY COLUMN `weight_from` real not null;
ALTER TABLE `shipping_rates` MODIFY COLUMN `weight_to` real not null;
ALTER TABLE `sports` MODIFY COLUMN `slug` varchar(40) not null;
ALTER TABLE `sports_teams` MODIFY COLUMN `aliases` text default ('');
ALTER TABLE `team_invitations` MODIFY COLUMN `team_id` bigint not null;
ALTER TABLE `team_invitations` MODIFY COLUMN `token_hash` varchar(64) not null;
ALTER TABLE `team_members` MODIFY COLUMN `team_id` bigint not null;
ALTER TABLE `team_members` MODIFY COLUMN `user_id` bigint not null;
ALTER TABLE `trade_decisions` MODIFY COLUMN `trading_strategy_id` bigint;
ALTER TABLE `trade_decisions` MODIFY COLUMN `prediction_market_id` bigint;
ALTER TABLE `trading_strategies` MODIFY COLUMN `user_id` bigint;
ALTER TABLE `categorizable_models` MODIFY COLUMN `id` bigint;
ALTER TABLE `categorizable_models` MODIFY COLUMN `category_id` bigint not null;
ALTER TABLE `categorizable_models` MODIFY COLUMN `categorizable_id` bigint not null;
ALTER TABLE `categorizable_models` MODIFY COLUMN `categorizable_type` varchar(255) not null default 'posts';
ALTER TABLE `categorizable_models` MODIFY COLUMN `created_at` datetime not null default CURRENT_TIMESTAMP;
ALTER TABLE `taggable_models` MODIFY COLUMN `id` bigint;
ALTER TABLE `taggable_models` MODIFY COLUMN `taggable_id` bigint not null;
ALTER TABLE `taggable_models` MODIFY COLUMN `tag_id` bigint not null;
ALTER TABLE `taggable_models` MODIFY COLUMN `taggable_type` varchar(255) not null default 'posts';
ALTER TABLE `taggable_models` MODIFY COLUMN `created_at` datetime not null default CURRENT_TIMESTAMP;
